saveExact: true

allowBuilds:
  "@parcel/watcher": true
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  msw: set this to true or false
  sharp: true
  workerd: set this to true or false
