/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as FileIndexRouteImport } from './routes/file/index'
import { Route as DatasetIndexRouteImport } from './routes/dataset/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as TableValidateRouteImport } from './routes/table/validate'
import { Route as TablePreviewRouteImport } from './routes/table/preview'
import { Route as TableInferSchemaRouteImport } from './routes/table/infer-schema'
import { Route as FileValidateRouteImport } from './routes/file/validate'
import { Route as FileInferDialectRouteImport } from './routes/file/infer-dialect'
import { Route as DatasetValidateRouteImport } from './routes/dataset/validate'
import { Route as DatasetInferRouteImport } from './routes/dataset/infer'
import { Route as DataValidateRouteImport } from './routes/data/validate'
import { Route as DataInferSchemaRouteImport } from './routes/data/infer-schema'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileIndexRoute = FileIndexRouteImport.update({
  id: '/file/',
  path: '/file/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetIndexRoute = DatasetIndexRouteImport.update({
  id: '/dataset/',
  path: '/dataset/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableValidateRoute = TableValidateRouteImport.update({
  id: '/table/validate',
  path: '/table/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const TablePreviewRoute = TablePreviewRouteImport.update({
  id: '/table/preview',
  path: '/table/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TableInferSchemaRoute = TableInferSchemaRouteImport.update({
  id: '/table/infer-schema',
  path: '/table/infer-schema',
  getParentRoute: () => rootRouteImport,
} as any)
const FileValidateRoute = FileValidateRouteImport.update({
  id: '/file/validate',
  path: '/file/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const FileInferDialectRoute = FileInferDialectRouteImport.update({
  id: '/file/infer-dialect',
  path: '/file/infer-dialect',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetValidateRoute = DatasetValidateRouteImport.update({
  id: '/dataset/validate',
  path: '/dataset/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetInferRoute = DatasetInferRouteImport.update({
  id: '/dataset/infer',
  path: '/dataset/infer',
  getParentRoute: () => rootRouteImport,
} as any)
const DataValidateRoute = DataValidateRouteImport.update({
  id: '/data/validate',
  path: '/data/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const DataInferSchemaRoute = DataInferSchemaRouteImport.update({
  id: '/data/infer-schema',
  path: '/data/infer-schema',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data/infer-schema': typeof DataInferSchemaRoute
  '/data/validate': typeof DataValidateRoute
  '/dataset/infer': typeof DatasetInferRoute
  '/dataset/validate': typeof DatasetValidateRoute
  '/file/infer-dialect': typeof FileInferDialectRoute
  '/file/validate': typeof FileValidateRoute
  '/table/infer-schema': typeof TableInferSchemaRoute
  '/table/preview': typeof TablePreviewRoute
  '/table/validate': typeof TableValidateRoute
  '/data/': typeof DataIndexRoute
  '/dataset/': typeof DatasetIndexRoute
  '/file/': typeof FileIndexRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data/infer-schema': typeof DataInferSchemaRoute
  '/data/validate': typeof DataValidateRoute
  '/dataset/infer': typeof DatasetInferRoute
  '/dataset/validate': typeof DatasetValidateRoute
  '/file/infer-dialect': typeof FileInferDialectRoute
  '/file/validate': typeof FileValidateRoute
  '/table/infer-schema': typeof TableInferSchemaRoute
  '/table/preview': typeof TablePreviewRoute
  '/table/validate': typeof TableValidateRoute
  '/data': typeof DataIndexRoute
  '/dataset': typeof DatasetIndexRoute
  '/file': typeof FileIndexRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data/infer-schema': typeof DataInferSchemaRoute
  '/data/validate': typeof DataValidateRoute
  '/dataset/infer': typeof DatasetInferRoute
  '/dataset/validate': typeof DatasetValidateRoute
  '/file/infer-dialect': typeof FileInferDialectRoute
  '/file/validate': typeof FileValidateRoute
  '/table/infer-schema': typeof TableInferSchemaRoute
  '/table/preview': typeof TablePreviewRoute
  '/table/validate': typeof TableValidateRoute
  '/data/': typeof DataIndexRoute
  '/dataset/': typeof DatasetIndexRoute
  '/file/': typeof FileIndexRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data/infer-schema'
    | '/data/validate'
    | '/dataset/infer'
    | '/dataset/validate'
    | '/file/infer-dialect'
    | '/file/validate'
    | '/table/infer-schema'
    | '/table/preview'
    | '/table/validate'
    | '/data/'
    | '/dataset/'
    | '/file/'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data/infer-schema'
    | '/data/validate'
    | '/dataset/infer'
    | '/dataset/validate'
    | '/file/infer-dialect'
    | '/file/validate'
    | '/table/infer-schema'
    | '/table/preview'
    | '/table/validate'
    | '/data'
    | '/dataset'
    | '/file'
    | '/table'
  id:
    | '__root__'
    | '/'
    | '/data/infer-schema'
    | '/data/validate'
    | '/dataset/infer'
    | '/dataset/validate'
    | '/file/infer-dialect'
    | '/file/validate'
    | '/table/infer-schema'
    | '/table/preview'
    | '/table/validate'
    | '/data/'
    | '/dataset/'
    | '/file/'
    | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataInferSchemaRoute: typeof DataInferSchemaRoute
  DataValidateRoute: typeof DataValidateRoute
  DatasetInferRoute: typeof DatasetInferRoute
  DatasetValidateRoute: typeof DatasetValidateRoute
  FileInferDialectRoute: typeof FileInferDialectRoute
  FileValidateRoute: typeof FileValidateRoute
  TableInferSchemaRoute: typeof TableInferSchemaRoute
  TablePreviewRoute: typeof TablePreviewRoute
  TableValidateRoute: typeof TableValidateRoute
  DataIndexRoute: typeof DataIndexRoute
  DatasetIndexRoute: typeof DatasetIndexRoute
  FileIndexRoute: typeof FileIndexRoute
  TableIndexRoute: typeof TableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/': {
      id: '/file/'
      path: '/file'
      fullPath: '/file/'
      preLoaderRoute: typeof FileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset/': {
      id: '/dataset/'
      path: '/dataset'
      fullPath: '/dataset/'
      preLoaderRoute: typeof DatasetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/validate': {
      id: '/table/validate'
      path: '/table/validate'
      fullPath: '/table/validate'
      preLoaderRoute: typeof TableValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/preview': {
      id: '/table/preview'
      path: '/table/preview'
      fullPath: '/table/preview'
      preLoaderRoute: typeof TablePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/infer-schema': {
      id: '/table/infer-schema'
      path: '/table/infer-schema'
      fullPath: '/table/infer-schema'
      preLoaderRoute: typeof TableInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/validate': {
      id: '/file/validate'
      path: '/file/validate'
      fullPath: '/file/validate'
      preLoaderRoute: typeof FileValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/infer-dialect': {
      id: '/file/infer-dialect'
      path: '/file/infer-dialect'
      fullPath: '/file/infer-dialect'
      preLoaderRoute: typeof FileInferDialectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset/validate': {
      id: '/dataset/validate'
      path: '/dataset/validate'
      fullPath: '/dataset/validate'
      preLoaderRoute: typeof DatasetValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset/infer': {
      id: '/dataset/infer'
      path: '/dataset/infer'
      fullPath: '/dataset/infer'
      preLoaderRoute: typeof DatasetInferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/validate': {
      id: '/data/validate'
      path: '/data/validate'
      fullPath: '/data/validate'
      preLoaderRoute: typeof DataValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/infer-schema': {
      id: '/data/infer-schema'
      path: '/data/infer-schema'
      fullPath: '/data/infer-schema'
      preLoaderRoute: typeof DataInferSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataInferSchemaRoute: DataInferSchemaRoute,
  DataValidateRoute: DataValidateRoute,
  DatasetInferRoute: DatasetInferRoute,
  DatasetValidateRoute: DatasetValidateRoute,
  FileInferDialectRoute: FileInferDialectRoute,
  FileValidateRoute: FileValidateRoute,
  TableInferSchemaRoute: TableInferSchemaRoute,
  TablePreviewRoute: TablePreviewRoute,
  TableValidateRoute: TableValidateRoute,
  DataIndexRoute: DataIndexRoute,
  DatasetIndexRoute: DatasetIndexRoute,
  FileIndexRoute: FileIndexRoute,
  TableIndexRoute: TableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
