import { Share2, Upload } from "lucide-react"
import { detectPlatform } from "#helpers/platform.ts"

export {
  AlertCircle as Danger,
  AlertTriangle as Warning,
  ArrowBigLeftDash as Return,
  Ban as Fault,
  AppWindow,
  BarChart,
  BookOpen as Book,
  Box as Dataset,
  Building,
  Car,
  CheckCircle as Success,
  Code,
  CodeXml,
  CircleHelp as Help,
  CornerDownLeft as Enter,
  Download,
  ExternalLink,
  FileJson as Data,
  FilePlusCorner as Add,
  FileText as Text,
  Github as GitHub,
  Globe as Url,
  GraduationCap as Guide,
  Group,
  History,
  House,
  Info as Note,
  Keyboard,
  Languages as Language,
  Lightbulb as Tip,
  Link2 as Link,
  Link2 as Stats,
  ListCheck as Channel,
  Loader as Pending,
  LogIn,
  LogOut,
  Map,
  Megaphone,
  Menu,
  Moon as DarkTheme,
  RefreshCw as Refresh,
  Rocket as Plan,
  Rss as Feed,
  Search,
  Settings,
  SlidersHorizontal as Filter,
  Sparkles,
  Star,
  Store,
  Sun as LightTheme,
  Table,
  Tag,
  Trash2 as Delete,
  TrendingUp,
  Upload,
  Upload as File,
  User as Account,
  X as Close,
  XCircle as Error,
} from "lucide-react"

export const Share = detectPlatform() === "ios" ? Upload : Share2
